### ISSUE TITLE
does not create automatically /var/log/journal

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/node-problem-detector#121]
Hi,

1. great initiative. Here is my experience on RHEL/CentOS 7

2. Apparently node-problem-detector is not able to work with the /run/log/journal/ (unfortunately) - correct? If so, it seems like a big limitation, no? 

3. The issue is that even if cannot do that, it also fails to start, as it depends on the existence of "/var/log/journal".  Knowing that it's not able to use /run/log/journal, is it reasonable to expect that it will create "/var/log/journal" on each node?

4. "/var/log/kern.log" is missing on my OS. I guess it's not in use any longer or it should be configured?

Here are the logs:

```
I0621 14:32:46.173199       7 log_watchers.go:40] Use log watcher of plugin "journald"
I0621 14:32:46.186164       7 log_monitor.go:72] Finish parsing log monitor config file: {WatcherConfig:{Plugin:filelog PluginConfig:map[timestamp:^.{15} message:kernel: \[.*\] (.*) timestampFormat:Jan _2 15:04:05] LogPath:/var/log/kern.log Lookback:5m} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status:false Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Kill process \d+ (.+) score \d+ or sacrifice child\nKilled process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB} {Type:temporary Condition: Reason:TaskHung Pattern:task \S+:\w+ blocked for more than \w+ seconds\.} {Type:temporary Condition: Reason:UnregisterNetDevice Pattern:unregister_netdevice: waiting for \w+ to become free. Usage count = \d+} {Type:temporary Condition: Reason:KernelOops Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelOops Pattern:divide error: 0000 \[#\d+\] SMP} {Type:permanent Condition:KernelDeadlock Reason:AUFSUmountHung Pattern:task umount\.aufs:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:DockerHung Pattern:task docker:\w+ blocked for more than \w+ seconds\.}]}
I0621 14:32:46.186204       7 log_watchers.go:40] Use log watcher of plugin "filelog"
I0621 14:32:46.186926       7 log_monitor.go:81] Start log monitor
E0621 14:32:46.186945       7 problem_detector.go:65] Failed to start log monitor "/config/kernel-monitor.json": failed to stat the log path "/var/log/journal": stat /var/log/journal: no such file or directory
I0621 14:32:46.186951       7 log_monitor.go:81] Start log monitor
E0621 14:32:46.186958       7 problem_detector.go:65] Failed to start log monitor "/config/kernel-monitor-filelog.json": failed to stat the file "/var/log/kern.log": stat /var/log/kern.log: no such file or directory
F0621 14:32:46.186964       7 node_problem_detector.go:88] Problem detector failed with error: no log montior is successfully setup
```

**Comment by Random-Liu** [comment]
great initiative. Here is my experience on RHEL/CentOS 7

> Apparently node-problem-detector is not able to work with the /run/log/journal/ (unfortunately) - correct? If so, it seems like a big limitation, no?

Are you running NPD in container or directly on the node?
* If it's the former one, you could always mount journal to `/var/log/journal` inside the container, e.g. `docker run -v /run/log/journal:/var/log/journal ...`.
* If it's the later one, you could [update configure](https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json#L6) to let NPD read from `/run/log/journal`.

> The issue is that even if cannot do that, it also fails to start, as it depends on the existence of "/var/log/journal". Knowing that it's not able to use /run/log/journal, is it reasonable to expect that it will create "/var/log/journal" on each node?

It's a bug https://github.com/kubernetes/node-problem-detector/issues/102, we haven't got time to fix it yet. :(

> "/var/log/kern.log" is missing on my OS. I guess it's not in use any longer or it should be configured?

On journald node, we don't expect `/var/log/kern.log` to be there.

I guess you are using `kube-up.sh`.
In kube-up.sh, we [start NPD with 2 different sets of configurations](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/node-problem-detector/npd.yaml#L51), one for journald node, one for rsyslog node. 2 system log watcher will be started, but only one is expected to work at a time. We made this trick because in a Kubernetes cluster, master and node may be using different OS distros, but we only have one NPD daemonset which has to support both distros.

**Comment by ReSearchITEng** [comment]
No, I am not using kube-up.sh, I am using kubeadm in ansible, on prem, using: https://github.com/ReSearchITEng/kubeadm-playbook/
Inside, I am using:  https://github.com/kubernetes/kubernetes/raw/master/cluster/addons/node-problem-detector/npd.yaml -> therefore /var/log is being mounted inside.
I noticed #102, it's related to it, but different.

I would like to emphasize the feature request: /run/log/journal in parallel with the /var/log/journal.

**Comment by xiuli2** [comment]
@Random-Liu  except for manually creating /var/log/journal and "var/log/kern.log",  also need manually create "var/log/docker.log", I think this is the similar bug with "/var/log/kern.log" is missing on my OS. I guess it's not in use any longer or it should be configured?" which was mentioned above.

Environment:  Red Hat Enterprise Linux Server release 7.4 (Maipo)
