### ISSUE TITLE
what about the  remedy system?

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/node-problem-detector#126]
Now I have deployed the node-problem-detector in my cluster and defines some new node condition type, but only to find that I can do nothing about the new condition like KernelHasDeadlock, I read the doc talking about remedy system, I think it is a controller like nodeController kind of thing, I wonder is there any plan about this remedy system and If I want to define my own, where can I start? Thanks in advance.

**Comment by Random-Liu** [comment]
@WIZARD-CXY We don't have plan to work on open source remedy system yet, because problems are usually very environment specific.

It's still possible to have a generic opensource remedy system which makes decision based on some configurable rules or more intelligent algorithms, but it's not prioritized yet.

In GKE, we have a auto-repair system which makes repair decision based on signal from NPD, you could easily build a similar component in your environment. :)

**Comment by WIZARD-CXY** [comment]
Oh, last day when I use GKE, I found this feature: "node auto-repair ". I find it is interesting, can I get more info on this feature?

**Comment by HardikDR** [comment]
As I understood remedy system would eventually be a controller listening for the events from the NPD.
Wondering if there is any proposal already put for the architecture of the controller ?

`In GKE, we have a auto-repair system which makes repair decision based on signal from NPD, you could easily build a similar component in your environment. :)`
I could not find much around whats mentioned..
Do we have more insights around node-auto repair ?

**Comment by WIZARD-CXY** [comment]
@HardikDR your idea is right, U can write a new controller which mimics the node controller in controller-manager to get it work. U may find this https://www.youtube.com/watch?v=U2Bm-Fs3b7Q useful
