### ISSUE TITLE
LOG fails got parsed

### ISSUE THREAD

**Issue by weinliu** [kubernetes/node-problem-detector#167]
Hi @joelsmith ,

I used Log Generator to get logs for kernel-monitor-filelog.json
https://github.com/kubernetes/node-problem-detector/tree/master/test/kernel_log_generator

```
export PROBLEM=problems/unregister_netdevice
export LOG_PATH=/var/log/kern.log
./generator.sh 
```

But it fails to get parsed on pods (logs)
```
...
W0403 06:50:45.624741       1 log_watcher.go:127] Unable to parse line: "Jan _2 15:04:05 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1\n", failed to parse timestamp "Jan _2 15:04:05": parsing time "Jan _2 15:04:05" as "Jan _2 15:04:05": cannot parse "_2 15:04:05" as "_2"
W0403 06:50:45.624752       1 log_watcher.go:127] Unable to parse line: "Jan _2 15:04:05 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1\n", failed to parse timestamp "Jan _2 15:04:05": parsing time "Jan _2 15:04:05" as "Jan _2 15:04:05": cannot parse "_2 15:04:05" as "_2"
...
```

Any suggestions for generating the log?

The same issue for docker logs
docker-monitor-filelog.json

```
cat /var/log/docker.log
...
W0404 03:35:35.173973       1 log_watcher.go:127] Unable to parse line: "time=\"(2008-01-02T15:04:05.999999999-07:00)\" failed to register layer: rename /var/lib/docker/image/overlay/layerdb/tmp/layer-558969056 /var/lib/docker/image/overlay/layerdb/sha256/3d979a98dc302b351aec55cf58f1b2bd86880c57df9553fb4fe0f94087f04e0b: directory not empty\n", failed to parse timestamp "(2008-01-02T15:04:05.999999999-07:00)": parsing time "(2008-01-02T15:04:05.999999999-07:00)" as "2006-01-02T15:04:05.999999999-07:00": cannot parse "(2008-01-02T15:04:05.999999999-07:00)" as "2006"
...
```

**Comment by joelsmith** [comment]
@weinliu The `generator.sh` script is for simulating kernel events via the system's logging process. The idea is that you send a message to `/dev/kmsg` which will act as though the kernel created the log message. With that in mind, it's probably not a good idea to append to a log file that a system logger is writing to. Especially since the `generator.sh` script does not format log messages the same way that the system logger would.

The NPD config files are often platform dependent. They need to be configured to read from the system log files for the platform where NPD is running. For example RHEL and CentOS will usually put their kernel messages in `/var/log/messages`, while Ubuntu and Debian will put them in `/var/log/kern.log`.  Additionally, different systems may use different timestamp formats, meaning that the NPD config will need to be updated to be able parse the timestamp.

Before we can tell what the problem is, we need more details about how you're running into it. It looks to me as though you're constructing log messages from the log regular expressions and the time parsing strings. This isn't going to work because many of the characters have special meaning in the context of a regular expression or a time parsing string. For example, the time parsing string `Jan _2 15:04:05` won't be able to match the invalid time string `Jan _2 15:04:05` (extra underscore, which has special meaning to the time parser), but will happily parse `Apr 11 09:30:12` or `Feb  3 19:59:03`.

Likewise, the regular expressions `^time="(\S*)"` and `msg="([^\n]*)" and the timestamp format `2006-01-02T15:04:05.999999999-07:00` won't properly match on the string:

```
time="(2008-01-02T15:04:05.999999999-07:00)" failed to register layer: rename /var/lib/docker/image/overlay/layerdb/tmp/layer-558969056 /var/lib/docker/image/overlay/layerdb/sha256/3d979a98dc302b351aec55cf58f1b2bd86880c57df9553fb4fe0f94087f04e0b: directory not empty
```
But should match on this string:
```
time="2017-02-17T19:55:16.618262556Z" level=error msg="Error trying v2 registry: failed to register layer: devicemapper: Error running deviceResume dm_task_run failed"
```

**Comment by weinliu** [comment]
Thanks for the detailed explanation.
