### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/node-problem-detector#282]
#### NPD Version
v0.6.3
#### Kernel version
4.15.0
#### What happened?
Kernel log got hammered with a lot of OOM kills. Totaling to about 4500 in a minute. This led to an extremely high CPU usage by node-problem-detector.

At a cursory glance, most of the time is spent in the kmsg's watchLoop. I've used Linux's `perf` utility, because I had no time to debug the issue properly with `go tool pprof`.

I'll try to find some time for the benchmarks, just leaving this here for now.

![image](https://user-images.githubusercontent.com/950313/58588038-6d63a500-8267-11e9-899f-baa1970dc86d.png)

**Comment by xueweiz** [comment]
/assign @xueweiz 
Thanks for filing the issue! I wanted to do some performance testing & improvement on NPD as well.

I think we should make sure NPD's resource consumption (cpu, mem, IO) always get bounded.
i.e. If there is a million problem going on, NPD should restrain from using too much resource detecting & reporting these problems. It's better to detect and report the issues slowly, rather than further punish the system by taking more resource away.

We could start with putting a CPU usage capacity on NPD. I think we could either use cgroup/cpulimit to limit NPD's CPU usage. We could add a systemd unit for starting NPD with recommended configuration under [node-problem-detector/deployment](https://github.com/kubernetes/node-problem-detector/tree/v0.6.3/deployment)/systemd/

@wangzhen127 WDYT?

@zuzzas Hi, I wonder if you are running NPD as a [standalone daemon](https://github.com/kubernetes/node-problem-detector/tree/v0.6.3#start-standalone) or as a [Kubernetes DaemonSet](https://github.com/kubernetes/node-problem-detector/tree/v0.6.3#installation)? And if you are running it as a standalone daemon, I wonder if your OS has system? Thanks!

**Comment by wangzhen127** [comment]
> I think we should make sure NPD's resource consumption (cpu, mem, IO) always get bounded.
i.e. If there is a million problem going on, NPD should restrain from using too much resource detecting & reporting these problems. It's better to detect and report the issues slowly, rather than further punish the system by taking more resource away.

Totally agree.

> We could start with putting a CPU usage capacity on NPD. I think we could either use cgroup/cpulimit to limit NPD's CPU usage. We could add a systemd unit for starting NPD with recommended configuration under node-problem-detector/deployment/systemd/

This can be the starting point. I think the problem is that NPD still needs to that much amount of work, it just becomes slower.

I think a better (and long term) way is to define the priority of the problems. When NPD found itself approaching the resource usage limit, it should try to complete the high priority problem detentions first, and drop low priority things. Or have a "degrade" mode, where NPD can drop log entries in order to catch up with the log production within CPU limit.

cc @Random-Liu @andyxning @dchen1107 for thoughts.

**Comment by zuzzas** [comment]
@xueweiz 
As a DaemonSet. CPU Limits, obviously, worked, but the container got throttled into oblivion.
