### ISSUE TITLE
Prometheus metrics naming

### ISSUE THREAD

**Issue by HaveFun83** [kubernetes/node-problem-detector#326]
Maybe you can follow the prometheus naming metrics and label style-guide for the exported metrics?
https://prometheus.io/docs/practices/naming/
https://github.com/kubernetes/node-problem-detector/blob/e280e2075ada86d2bde947bb2ff0776575026734/pkg/problemmetrics/problem_metrics.go#L41-L42

**Comment by xueweiz** [comment]
/cc @wangzhen127 
/cc @Random-Liu 

Hi @HaveFun83 , I think we could rename `problemCounter` to `problemCount`. What do you think? And do you have any suggestion of a better naming for `problemGauge`? Thanks!

**Comment by xueweiz** [comment]
Oh I just realized maybe you meant that the metrics should be in snake case (`some_metric`) rather than camel case (`someMetric`). But I couldn't tell for sure.
Could you clarify what's your recommendation of what the metric names should be? Thanks!

**Comment by HaveFun83** [comment]
According to the prometheus naming docs i would suggest:
`nodeproblemdetector_problem_count_total`
`nodeproblemdetector_problem_type_info`

**Comment by HaveFun83** [comment]
any news here?

 /remove-lifecycle stale

**Comment by xueweiz** [comment]
Hi @HaveFun83 ,
I propose to rename the metrics to `problem_count_total` and `problem_state`. Does that fit your idea? And/or if you want, I could implement a command-line option to allow NPD user to choose any non-default value for this.

Here are the reasons for my proposal:
1. I prefer to not add the `nodeproblemdetector` prefix. Because when Prometheus scrapes the NPD metric endpoint, it's very easy to add a prefix as metrics domain. I think by adding the prefix, we restrict the flexibility of the users, say if they want to have a prefix such as "npd", "k8s-npd" or "gke-npd".
2. According to the below item in [the naming guide](https://prometheus.io/docs/practices/naming/), we should add the "total" for accumulating counts, and hence `problem_count_total`
    > ...should have a suffix describing the unit, in plural form. Note that an accumulating count has total as a suffix, in addition to the unit if applicable.
3. I didn't choose `problem_gauge_info`, because according to naming guide, "info" is used for:

    > a pseudo-metric that provides [metadata](https://www.robustperception.io/exposing-the-software-version-to-prometheus) about the running binary

   The value of the metrics actually is meaningful (0 v.s. 1), so I'd prefer to not use the info suffix.

4. I eventually chose `problem_state`, because I saw the `container_tasks_state` metric [reported](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) by cadvisor. This is very similar to their example: the metric defines the "state" of the problem, 0 means "not affecting the node" or "not happening", 1 means "affecting the node" or "happening".

Please let me know what you think :) Thanks!

**Comment by xueweiz** [comment]
@andyxning  Hi Ning, do you have any suggestions? :)

**Comment by xueweiz** [comment]
Hi @HaveFun83  :) If you don't have any other opinion, I'll just submit a PR for [this proposal](https://github.com/kubernetes/node-problem-detector/issues/326#issuecomment-555808115) :P

**Comment by HaveFun83** [comment]
> Hi @HaveFun83 ,
> I propose to rename the metrics to `problem_count_total` and `problem_state`. Does that fit your idea? And/or if you want, I could implement a command-line option to allow NPD user to choose any non-default value for this.
> 
> Here are the reasons for my proposal:
> 
>     1. I prefer to not add the `nodeproblemdetector` prefix. Because when Prometheus scrapes the NPD metric endpoint, it's very easy to add a prefix as metrics domain. I think by adding the prefix, we restrict the flexibility of the users, say if they want to have a prefix such as "npd", "k8s-npd" or "gke-npd".
> 
>     2. According to the below item in [the naming guide](https://prometheus.io/docs/practices/naming/), we should add the "total" for accumulating counts, and hence `problem_count_total`
>        > ...should have a suffix describing the unit, in plural form. Note that an accumulating count has total as a suffix, in addition to the unit if applicable.
> 
>     3. I didn't choose `problem_gauge_info`, because according to naming guide, "info" is used for:
>        > a pseudo-metric that provides [metadata](https://www.robustperception.io/exposing-the-software-version-to-prometheus) about the running binary
>        
>        
>        The value of the metrics actually is meaningful (0 v.s. 1), so I'd prefer to not use the info suffix.
> 
>     4. I eventually chose `problem_state`, because I saw the `container_tasks_state` metric [reported](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) by cadvisor. This is very similar to their example: the metric defines the "state" of the problem, 0 means "not affecting the node" or "not happening", 1 means "affecting the node" or "happening".
> 
> 
> Please let me know what you think :) Thanks!

Sorry for the late response.
yeah your right. Sounds good to me. Thanks for the details explanation.

**Comment by xueweiz** [comment]
@HaveFun83 , #401 implements this. Could you help take a look as well? Thanks!

**Comment by HaveFun83** [comment]
/remove-lifecycle rotten

There are still some work on the PR #401

**Comment by HaveFun83** [comment]
any news here?

**Comment by xueweiz** [comment]
I sent #401 , but I think Zhen and Lantao are pretty busy these days to review the PR. Let me try Andy instead.

**Comment by HaveFun83** [comment]
any news here?
