### ISSUE TITLE
Add a Dockerfile that can work as development environment

### ISSUE THREAD

**Issue by grosser** [kubernetes/node-problem-detector#360]
I tried to get this building on mac and failed because it needs systemd

```
make build
CGO_ENABLED=1 GOOS=linux GO111MODULE=on go build \
		-mod vendor \
		-o bin/node-problem-detector \
		-ldflags '-X k8s.io/node-problem-detector/pkg/version.version=v0.7.1-19-g219b408' \
		-tags """ journald" \
		./cmd/nodeproblemdetector
# github.com/coreos/go-systemd/sdjournal
vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:11: fatal error: 'systemd/sd-journal.h' file not found
 #include <systemd/sd-journal.h>
```

and ideally some instructions for that in the readme

**Comment by xueweiz** [comment]
Mac does not use [systemd-journald](https://wiki.archlinux.org/index.php/Systemd/Journal), so you cannot enable journald-related features in NPD. The only way I know to make NPD work on Mac, is to set [`ENABLE_JOURNALD`](https://github.com/kubernetes/node-problem-detector/blob/d000c1b060803cb8b3172fdcf9aa9956db942d7e/Makefile#L51) to 0, which disables these features.

Can you try to start a Ubuntu container on Mac, and install "libsystemd-dev", then try to compile NPD in that environment?
Since I don't have a Mac, I don't know whether it works or not. If you could let me know, that'd be great.

**Comment by grosser** [comment]
yeah ubuntu container would work
I'm not saying it should work, but having some "Systemd is not installed, use ENABLE_JOURNALD=0" would be nice :)
... closing since the ENABLE_JOURNALD=0 now actually works and it's not too hard to find

**Comment by xueweiz** [comment]
> having some "Systemd is not installed, use ENABLE_JOURNALD=0" would be nice :)

I totally agree!
I [thought about](https://github.com/kubernetes/node-problem-detector/pull/384#issuecomment-551363103) adding a Makefile rule such as `checkDependency` to do this. Just hasn't put too much effort into it.
