### ISSUE TITLE
custom plugin is blocked due to the timeout of my plugin script 

### ISSUE THREAD

**Issue by zjumoon01** [kubernetes/node-problem-detector#372]
I'm beginning to learn and test npd. When I try to use custom plugin and its timeout, I found an issue which I'm not sure it is a 'real' issue.

npd start cmd
`bin/node-problem-detector --v=2 --logtostderr --enable-k8s-exporter=false  --config.custom-plugin-monitor=./config/custom-plugin-monitor.json` 

#cat ./config/custom-plugin-monitor.json
{
  "plugin": "custom",
  "pluginConfig": {
    "invoke_interval": "30s",
    "timeout": "20s",
    "max_output_length": 80,
    "concurrency": 2,
    "enable_message_change_based_condition_update": false
  },
  "metricsReporting": true,
  "rules": [
    {
      "type": "temporary",
      "reason": "NTPIsDown",
      "path": "./config/plugin/check_ntp.sh",
      "timeout": "10s"
    },
    {
      "type": "temporary",
      "reason": "PidUsageExceed",
      "path": "./config/plugin/check_pid.sh",
      "timeout": "15s"
    },
    {
      "type": "temporary",
      "reason": "CollectdRunOnDocker",
      "path": "./config/plugin/check_collectd_for_docker.sh",
      "timeout": "8s"
    }
  ]
}

There are 3 scripts: check_ntp.sh, check_pid.sh, check_collectd_for_docker.sh.
I injected "sleep 200" into check_ntp.sh
```
#cat ./config/plugin/check_ntp.sh
#!/bin/bash

OK=0
NONOK=1
UNKNOWN=2

sleep 200

which systemctl >/dev/null
if [ $? -ne 0 ]; then
    echo "Systemd is not supported"
    exit $UNKNOWN
fi

systemctl status ntp.service | grep 'Active:' | grep -q running
if [ $? -ne 0 ]; then
    echo "NTP service is not running"
    exit $NONOK
fi

echo "NTP service is running"
exit $OK
```

When time is up to 10s,  npd sends kill signal to check_ntp.sh. Script check_ntp.sh can be killed successfully, but its child process "sleep 200" is still running which new parent is the process pid 1. 
The result is that custom plugin is blocked until "sleep 200" ends although check_ntp.sh is killed. After 200 seconds, I can see log
`Message:Timeout when running plugin "./config/plugin/check_ntp.sh": state - signal: kill`

So I think there are two problems in this scenario:
1. Script in custom plugin rules will be still waiting after timeout.
2. Other scripts are also blocked. They will not be invoked as expected in "invoke_interval 30s" and "concurrency 2".

IMO, Can we use the action as "kill -TERM -PID" to send kill signal to script and its children processes when timeout comes? Or one script's blocking won't block other scripts.

**Comment by xueweiz** [comment]
This is interesting. I verified this, turns out the [`cmd.Output()`](https://github.com/kubernetes/node-problem-detector/blob/ef30a1fdd173198d1ce6475d6ed1f698759cee72/pkg/custompluginmonitor/plugin/plugin.go#L131) will block until `sleep 200` finishes. This is not the intention. The intention is that it should unblock as soon as the [timer](https://github.com/kubernetes/node-problem-detector/blob/ef30a1fdd173198d1ce6475d6ed1f698759cee72/pkg/custompluginmonitor/plugin/plugin.go#L124) expires.

One way to fix it is to implement something like [this](https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773), basically create a process group for each plugin invocation, and then just kill the process group.

However, I still haven't understand why would `cmd.Output()` block in our case. When the child process is killed, but there are orphan processes created by the child process, I'd expect `cmd.Output()` to finish. I'm suspecting that this might be a go library bug. Please let me know if I'm wrong. Thanks!
