### ISSUE TITLE
some checksum mismatch for go 1.13

### ISSUE THREAD

**Issue by yuzhiquan** [kubernetes/node-problem-detector#396]
go version
```
go version go1.13.4 linux/amd64
```

build with go mod, not go path or vendor

```
verifying k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible: checksum mismatch
        downloaded: h1:A5pdeNsAyGjohGD5QrSFEto0ndr0yDWnbgZIFWvNHp0=
        go.sum:     h1:6cZzf9MH9iOiZqO7bn7A9sadvF9T7jgwkIPUo30iHBY=
```
and
```
verifying k8s.io/kubernetes@v1.14.6: checksum mismatch
        downloaded: h1:t8Q3aaWanmiariBBr3qYIcAL9o0pv4MB5tZtfbILJGk=
        go.sum:     h1:cwv2BD3ZlbMg0NRuRs+d9H0mJEKXYQCcv1RqhLQrmvo=
```
mv go.sum, then `go tidy`, but 
```
╰─ go mod tidy                                                                                                                                                                           
verifying github.com/euank/go-kmsg-parser@v2.0.1+incompatible/go.mod: github.com/euank/go-kmsg-parser@v2.0.1+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/euank/go-kmsg-parser@v2.0.1+incompatible: 410 Gone
```

root-causes likely [go-modules](https://golang.org/doc/go1.13#modules), so i modify go.sum manually, but not sure it's the rightway or not

**Comment by xueweiz** [comment]
Can you tell me what command to run to reproduce this error?

If it's a `go build xxx` command, then you should not do it. We should use `make` or `make build-binaries` to build them.

**Comment by yuzhiquan** [comment]
> Can you tell me what command to run to reproduce this error?
> 
> If it's a `go build xxx` command, then you should not do it. We should use `make` or `make build-binaries` to build them.

I build it with `cd cmd/nodeproblemdetector && go build`, so it's  a wrong way?

**Comment by xueweiz** [comment]
That explains it :) You should use `make` to compile it.

The [build image](https://github.com/kubernetes/node-problem-detector#build-image) section and the [try it out](https://github.com/kubernetes/node-problem-detector#try-it-out) section of the README explains about how to compile NPD.

`go build` won't work. Because compiling NPD requires some special compilation options. Those special options are implemented in the Makefile.

(make sure to install "systemd develop files" first. See the README for how to do it.

**Comment by yuzhiquan** [comment]
ok, get it.thanks
