### ISSUE TITLE
Missing documentation on using HealthChecker Problem Daemon

### ISSUE THREAD

**Issue by goatmale** [kubernetes/node-problem-detector#576]
Looking at the documentation it is unclear on how we can use the HealthChecker problem daemon. 

For SystemLogMonitor and SystemStatsMonitor there are clear flags (`--config.system-stats-monitor` and `--config.system-log-monitor`) which accept configuration files.

What is the proper process for enabling the HealthCheckers? It looks like they are custom plugin monitor, however the documentation lists them as a separate Daemon which is a bit confusing.

**Comment by vteratipally** [comment]
In order to enable the HealthCheck, we need to enable it through custom-plugin-monitor. NPD creates a daemon for each of the custom-plugins in order to monitor the system. This is why it is listed as a separate daemon. The Healther checker can be enabled by `--config.custom-plugin-monitor=/path/to/health-checker-docker.json or health-checker-containerd.json.
The health-checker-docker.json is present [here](https://github.com/kubernetes/node-problem-detector/blob/1e8008bdedbeae39074c93cfe3fcdad7735f4db1/config/health-checker-docker.json)

**Comment by goatmale** [comment]
> In order to enable the HealthCheck, we need to enable it through custom-plugin-monitor. NPD creates a daemon for each of the custom-plugins in order to monitor the system. This is why it is listed as a separate daemon. The Healther checker can be enabled by `--config.custom-plugin-monitor=/path/to/health-checker-docker.json or health-checker-containerd.json.
> The health-checker-docker.json is present [here](https://github.com/kubernetes/node-problem-detector/blob/1e8008bdedbeae39074c93cfe3fcdad7735f4db1/config/health-checker-docker.json)

Thanks @vteratipally - is there any documentation on what this plugin checks?
