### ISSUE TITLE
Bump the version to v0.3 in makefile, manifest and readme

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/node-problem-detector#60]
After adding the standalone mode in #49 , I created and pushed a new docker image gcr.io/google_containers/node-problem-detector:v0.3 which includes these changes for use by [kubemark](https://github.com/kubernetes/kubernetes/tree/master/test/kubemark). However this version bump has to be reflected in:
1. version tag inside the Makefile
2. image inside the node-problem-detector.yaml
3. readme, to indicate that v0.3 is the latest version and/or suggested for use?

@Random-Liu Hope this push doesn't disturb any plans you might be having for npd release schedule. If yes, it's not difficult to revert this change, as I just did it for use in kubemark.

**Comment by Random-Liu** [comment]
@shyamjvs 
I'm fine with releasing a v0.3 for now, because:
1) NPD can work now, except that:
  * Journald support is not working until https://github.com/kubernetes/node-problem-detector/pull/39 is merged.
  * Some RBAC setup is needed in a new K8s cluster https://github.com/kubernetes/node-problem-detector/issues/61.
2) This could unblock your kubemark work.

However, we should formalize the release process as soon as possible. https://github.com/kubernetes/node-problem-detector/issues/58

I planed to write a simple release process, but haven't got time. Hope I could finish it this week.

**Comment by Random-Liu** [comment]
Let's keep this issue open until I finish the release process, and update the Readme and changelog.

**Comment by patrickf55places** [comment]
@Random-Liu any progress on this issue (which should be updated to 0.4.1)?
