### ISSUE TITLE
License Scan and Findings

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/node-problem-detector#863]
- kubernetes-2024-01-03.zip/node-problem-detector/vendor/[github.com/shoenig/go-m1cpu/LICENSE](http://github.com/shoenig/go-m1cpu/LICENSE)
- kubernetes-2024-01-03.zip/node-problem-detector/vendor/[github.com/shoenig/go-m1cpu/README.md](http://github.com/shoenig/go-m1cpu/README.md)

This code is under the MPL-2.0 license which is weak copyleft. Be sure that it is used only as dynamic libraries, to be safe if it's not required remove it from your repo.

Like https://github.com/kubernetes/kubernetes/blob/master/hack/unwanted-dependencies.json

**Comment by jeffcshapiro** [comment]
Per Bob Killen @mrbobbytables
This has been granted a license exception approval:

[cncf-exceptions-2023-08-31.spdx](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2023-08-31.spdx)
[github.com/shoenig/go-m1cpu](http://github.com/shoenig/go-m1cpu) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2023-08-31

**Comment by pacoxu** [comment]
Thanks.
